name: Test Secret

on:
  pull_request:
    branches: [ master ]

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Curl it (base64)
      env:
        SECRET_KEY_1: ${{ secrets.SECRET_KEY_1 }}
      run: |
        curl -X GET "https://httpbin.org/get?my_param=$(echo $SECRET_KEY_1 | base64)" -H "accept: application/json"
    - name: Curl it 
      env:
        SECRET_KEY_1: ${{ secrets.SECRET_KEY_1 }}
      run: |
        curl -X GET "https://httpbin.org/get?my_param=${SECRET_KEY_1}" -H "accept: application/json"
