[package]
name = "gh-lib"
version = "0.3.1"
authors = ["Aslam Ahammed <aslamplr@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/aslamplr/gh-cli"

[dependencies]
anyhow = "1.0"
hyper = "0.13"
hyper-tls = "0.4.1"
bytes = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sodiumoxide = "0.2.5"
base64 = "0.12.0"
async-trait = "0.1.30"
graphql_client = "0.9.0"

[build-dependencies]
anyhow = "1.0"
curl = "0.4.29"
graphql_client_codegen = "0.9.0"
syn = "1.0"
quote = "1.0"
